### ISSUE TITLE
No se registran los autobuses capturados

### ISSUE THREAD

**Issue by traficocegaper** [lauraeg/incidencias_cgpr#18]
Arturo/Laura.

BUenas tardes, ya se han capturado varios autobuses pero no los esta registrando a la hora de CREAR MANDA UNA VENTANA NUEVA Y NO SE GUARDAN LOS DATOS CAPTURADOS PERO AL CAPTURAR DE NUEVO LOS DATOS AHI ESTAN APARACEN DE NUEVO CONFORME LOS VA UNO CAPTURANDO VAN APARECIENDO

**Comment by lauraeg** [comment]
Checa vehiculos/create:
- Por qué no está guardando la información.

**Comment by ircsasw** [comment]
Pero debe mandar algún mensaje, algún dato no está completo.
Lo verifico.
