### ISSUE TITLE
Reservaciones: Operadores y vehículos

### ISSUE THREAD

**Issue by lauraeg** [lauraeg/incidencias_cgpr#26]
- Operador, se asigne uno pero que permita ser modificado cuando se requiera
- Vehículo, se asigne uno pero que permita ser modificado cuando se requiera

--- Sugiero poner primera opción en la lista de ambos: "Pendiente por asignar"

**Comment by ircsasw** [comment]
Se pueden dejar sin llenar y en las vistas muestra "Pendiente por asignar.".
