### ISSUE TITLE
Clientes y Tarifas

### ISSUE THREAD

**Issue by lauraeg** [lauraeg/incidencias_cgpr#39]
- Capturen datos de clientes (sólo hay PÚBLICO EN GENERAL) Y TARIFAS para esos nuevos clientes.

**Comment by traficocegaper** [comment]
![image](https://cloud.githubusercontent.com/assets/10728514/7734551/527f2b80-fefc-11e4-8334-93ac134c8402.png)

**Comment by traficocegaper** [comment]
ESTANDO CAPTURANDO SALIO LA LEYENDA QUE DICE ASI
LA CONVINACION DE CLIENTE Y SERVICIO YA ESTA DEFINIDA Y NO SE QUE HACER 

SALUDOS

SERGIO

**Comment by lauraeg** [comment]
Quiere decir que ya existe en el tarifario una combinación Cliente-Servicio con esos datos exactos. Si necesita definir rangos de precios PARA ESE CLIENTE CON ESE SERVICIO, solamente localícelos y edítelos.
