### ISSUE TITLE
Tipos de vehículos

### ISSUE THREAD

**Issue by ircsasw** [lauraeg/incidencias_cgpr#4]
Definir una lista de tipos de vehículos.

Por el momento se definen los siguientes, verificar si son correctos y/o si hay otros.

1. Autobus
2. Crafter
3. Traffic
4. Van

**Comment by traficocegaper** [comment]
Autobus
Crafter
Transporter

**Comment by lauraeg** [comment]
@ircsasw

**Comment by ircsasw** [comment]
Listo.
