### ISSUE TITLE
NO SE QUE QUIERE DECIR ESA INSIDENCIA 

### ISSUE THREAD

**Issue by traficocegaper** [lauraeg/incidencias_cgpr#40]
![image](https://cloud.githubusercontent.com/assets/10728514/7734525/22119258-fefc-11e4-8739-a595b1eb390d.png)

**Comment by ircsasw** [comment]
Significa que ya se capturó una tarifa para ese cliente con ese servicio, y así es, lo puedes verificar en Tarifas/Administrar, ese cliente ya tiene tarifas para ese servicio.

Significa que no se pueden definir mas que una tarifa para un servicio de un cliente.

Si los precios han cambiado, lo correcto es editar los que ya están definidos para ese cliente+servicio.
