### ISSUE TITLE
Error en Reservaciones/view

### ISSUE THREAD

**Issue by lauraeg** [lauraeg/incidencias_cgpr#49]
/reservaciones/create, se captura con fecha-hora, y cita específicos

/reservaciones/update, se muestra con la fecha-hora y cita específicos capturados en /create
/reservaciones/view , muestra una hora diferente.

/reservaciones/calendario, muestra fecha-hora capturada en /create

**Comment by ircsasw** [comment]
Esto es en la WEB o en tu Local, si es en tu local quizá se tenga que configurar el "timezone" de tu sistema.
@RoyArgaez - verificar configuración

**Comment by lauraeg** [comment]
Lo checo, web no ha capturado nada en /reservaciones/create

**Comment by lauraeg** [comment]
Al guardar una nueva reservación me manda error:
![image](https://cloud.githubusercontent.com/assets/963627/8383925/e7b15c6e-1c02-11e5-96e0-f0ebe2d13012.png)
