### ISSUE TITLE
Un dato de Operadores

### ISSUE THREAD

**Issue by ircsasw** [lauraeg/incidencias_cgpr#5]
¿El dato *No. de gafete de Asur* es un dato necesario para el catálogo de Operadores?

**Comment by lauraeg** [comment]
@traficocegaper

**Comment by traficocegaper** [comment]
si

**Comment by RoyArgaez** [comment]
¿El *No. de gafete* solo lleva números o también letras? ¿Cuántos caracteres tiene?

**Comment by RoyArgaez** [comment]
Ha sido creado puede verificarse, en caso de modificaciones, favor de especificarla por este medio.

**Comment by traficocegaper** [comment]
el numero de gafete lleva una letra P espacio y 5 numeros

**Comment by lauraeg** [comment]
@traficocegaper  Se puso una "etiqueta Ej P 12345)" para orientar al capturista. NO SE RESTRINGIÓ a que la primera sea una consonante y sólo 5 dígitos. 

¿Es suficiente? o se restringe la captura?
