### ISSUE TITLE
Error en TODOS LOS GRIDS

### ISSUE THREAD

**Issue by lauraeg** [lauraeg/incidencias_cgpr#50]
Sale en todos los grids de cada opción: 

- [x] /reservaciones/operaciones
- [x] /reservaciones/index
- [x] /clientes/index
- [x] /servicios/index
- [x] /tarifas/index
- [x] /operadores/index
- [x] /vehiculos/index

![image](https://cloud.githubusercontent.com/assets/963627/7973881/905a2b4c-0a20-11e5-8158-7cd2db612c44.png)

**Comment by ircsasw** [comment]
Esto era un error en el servidor pero ya está funcionando desde que se reportó.
