### ISSUE TITLE
Mejora en todos los módulos ORTOGRAFÍA, faltan acentos /proveedores/create

### ISSUE THREAD

**Issue by lauraeg** [lauraeg/incidencias_cgpr#61]
- [x] RFC , en mayúsculas
- [x] DirecciÓn
- [x] PaÍs
- [x] TelÉfono, completo ya sea 1, 2....
- [x] CP
- [x] CrÉdito
- [x] DÍas

**Comment by ircsasw** [comment]
@RoyArgaez para teléfono maneja, Teléfono principal y Teléfono adicional.
