### ISSUE TITLE
Textos de ayuda en insumos/create

### ISSUE THREAD

**Issue by ircsasw** [lauraeg/incidencias_cgpr#72]
En los placeholder de cada campo correspondiente:

- [x] Clave: Clave o código de barras del insumo
- [ ] Unidad entra: Unidad de medida en la que entra al almacén
- [ ] Unidad sale: Unidad de medida en la que sale del almacén
- [x] Factor empaque: Valor de unidad de entrada
- [x] Unidades empaque: Valor de unidades resultantes por cada unidad de entrada
- [x] Máximo: Máximo de existencias óptimas
- [x] Mínimo: Mínimo de existencias óptimas
- [x] Apartados: Cantidad apartada (no disponibles)
- [x] Por surtir: Cantidad por surtir
- [x] Por recibir: Cantidad por recibir

**Comment by RoyArgaez** [comment]
"*Unidad Entra*" y "*Unidad sale*" Son Dropdown's
