### ISSUE TITLE
CATALOGO OPERADORES

### ISSUE THREAD

**Issue by traficocegaper** [lauraeg/incidencias_cgpr#8]
1.- EN REFERENCIA QUE SE VA A PONER AHÍ
2.-PUEDES CAMBIAR EL CONCEPTO DE TELÉFONO POR NEXTEL
3.- PUEDES COLOCAR UN CAMPO MAS EN DONDE APAREZCA NUMERO DE RADIO
4.-EN MENSAJERO QUE VA A AHI

**Comment by traficocegaper** [comment]
![pantalla1](https://cloud.githubusercontent.com/assets/10728514/5925465/4efbd070-a629-11e4-955d-1adfefa78e8e.png)

**Comment by lauraeg** [comment]
1.- EN REFERENCIA QUE SE VA A PONER AHÍ -
         P. ejem "Junto al parque, frente al colegio"
2.-PUEDES CAMBIAR EL CONCEPTO DE TELÉFONO POR NEXTEL - 
        Sería más conveniente "RADIO", no centrarlo en una marca? o Nextel y radio son diferentes?
3.- PUEDES COLOCAR UN CAMPO MAS EN DONDE APAREZCA NUMERO DE RADIO
       Qué tal si se diseña en el siguiente orden de captura: "RADIO" - "CELULAR" - "TELÉFONO FIJO"
4.-EN MENSAJERO QUE VA A AHI
      Se pone el contacto del skype, face, o tipo de mensajería online que se utilice.

**Comment by lauraeg** [comment]
Cambiar la etiqueta "Mensajero" por "ID Radio"
