### ISSUE TITLE
Detalles en site /settings/catalogos/familia

### ISSUE THREAD

**Issue by lauraeg** [lauraeg/incidencias_cgpr#83]
Cuando se da clic en "Catálogos /Familia" muestra /categorias/index; en el cual se Da de Alta a una nueva familia.. PERO, cuando se da clic en " Nuevo" pasa lo siguiente:
- El menú de Catálogos se contrae, lo cual no debe ser
- El título dice " Crear Categoría". Lo correcto es "Crear Familia"
- Después de guardar una nueva familia manda a la ventana /categorias/view SIN MOSTRAR EL COMANDO "NUEVO".  Entonces hay que desplegar nuevamente catálogos, familias y repetir el proceso.

**Comment by RoyArgaez** [comment]
Este issue está corregido
